name: Test

on:
  pull_request:
    branches: [trunk]

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            .github/workflows/test.yml
            src/*
            test/*
            cli.js
            package.json
            package-lock.json

  test:
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.status == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Node
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache
            ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
